# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true
################## Github ##################
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/u77w41/"

[social.params]
icon = "brand-github"
newtab = true
################## LinkedIn ##################
[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/ujjwalchowdhury0"

[social.params]
icon = "brand-linkedin"
newtab = true

################## X ##################
[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/UjjwalCh0wdhury"

[social.params]
icon = "brand-x"
newtab = true

################## Kaggle ##################
#[[social]]
#identifier = "kaggle"
#name = "Kaggle"
#url = "https://www.kaggle.com/ujjwalchowdhury"
#
#[social.params]
#icon = "brand-kaggle"
#newtab = true